version: "2"
volumes:
  node_modules:

services:
  relay:
    build:
      context: .
      dockerfile: Dockerfile.n2n2.testnet.lndrelay
    volumes:
      # - .:/relay
      # - .lnd/:/relay/.lnd
      - node_modules:/relay/node_modules
    ports:
      - "3000:3000"
      - "9735:9735"
      - "10009:10009"
      - "8333:8333"
    command: "lnd --accept-keysend --configfile=/relay/.lnd/lnd.conf && npm start"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NODE_DOMAIN=$NODE_DOMAIN
      - NODE_IP=$NODE_IP
      - NODE_ALIAS=$NODE_ALIAS
      - TRIBES_HOST=$TRIBES_HOST
      - MEDIA_HOST=$MEDIA_HOST
      - MACAROON_LOCATION=$MACAROON_LOCATION
